version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: ferreteria_db_prod
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres_data_prod:/var/lib/postgresql/data
    networks:
      - ferreteria_net

  backend:
    build: ./back
    container_name: ferreteria_api_prod
    restart: always
    ports:
      - "${PORT:-3000}:3000"
    environment:
      DATABASE_URL: postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}?schema=public
      JWT_SECRET: ${JWT_SECRET}
      PORT: 3000
    depends_on:
      - postgres
    networks:
      - ferreteria_net

volumes:
  postgres_data_prod:


networks:
  ferreteria_net:
